### ISSUE TITLE
Windows 10 installation

### ISSUE THREAD

**Issue by aruizbueno** [Quantico-Bullet/PyBeam-QA#2]
Hi Kagiso,

Congratulations for the great work done and thank you for sharing it.
I am trying to install pybeam-qa in Windows 10 using anaconda but without success. I follow these steps:
1.- I install anaconda
2.- I install pipenv, pyside6, pylinac, pyqtgraph and pdfrw 0.4 from anaconda prompt
3.- I run the app: >>>python main.py
I'm probably doing it wrong because I'm a newbie python user. Could you help me?

Greetings and thanks in advance,

Antonio

![error](https://github.com/Quantico-Bullet/PyBeam-QA/assets/115100038/aace3eea-62c4-473c-8505-f661159cd054)

**Comment by Quantico-Bullet** [comment]
Hi Antonio,

Thank you and apologies for the cumbersome installation process (😅 I'm still ironing out a few things before making the software available via PIP).

As for your problem, the operand `|` was added in python 3.10. I've also set 3.10+ as a requirement in the README section. 

Please confirm if your python version is not the issue

Thanks,

Kagiso

**Comment by aruizbueno** [comment]
Now it works using Python 3.12!
Apologies for the inconvenience.
Thanks,

Antonio

**Comment by Quantico-Bullet** [comment]
Hi Antonio

Thank you for your feedback. No inconvenience on my side, I'm always happy to help :)
